net/i40e: fix build for Windows MinGW
Adds extra cflags '-fno-asynchronous-unwind-tables'
to avoid the MinGW build error:
	Error: invalid register for .seh_savexmm

Fixes: 5c38c33f7880 ("net/i40e: disable AVX512 with MinGW")

Signed-off-by: Leyi Rong <leyi.rong@intel.com>
Tested-by: Dmitry Kozlyuk <dmitry.kozliuk@gmail.com>