examples/vm_power_manager: fix const discarding
[ upstream commit 629d136b2501aabb85a49205c049f71ed170c790 ]

When compiling with GCC 15.2.1, a const qualifier issue
is seen with this warning:

In function 'get_resource_name_from_chn_path':
examples/vm_power_manager/channel_monitor.c:139:16:
error: assignment discards 'const' qualifier from pointer target type
  139 | substr = strstr(channel_path, CHANNEL_MGR_FIFO_PATTERN_NAME);
      |        ^

The function get_resource_name_from_chn_path is used only once
and call a single function (strstr),
so it can be replaced with a direct call to strstr().

Fixes: 221e7026d521 ("examples/power: add FIFO per core for JSON interface")

Signed-off-by: Thomas Monjalon <thomas@monjalon.net>