ci: remove LTO job
The LTO job using gcc-7 has two issues at the moment:
- warnings about implicit fallthroughs trigger build errors:

In file included from ...common/include/rte_memory.h:22:0,
                 from ...linux/eal/eal_hugepage_info.c:24:
...common/include/rte_common.h: In function ‘rte_str_to_size’:
...common/include/rte_common.h:744:27: error: this statement may
  fall through [-Werror=implicit-fallthrough=]
  case 'G': case 'g': size *= 1024; /* fall-through */
                      ~~~~~^~~~~~~

- if we disable this warning, linking the binaries takes too much time
  and the job is terminated by Travis because it reaches the maximum
  time limit

Fixes: 098cc0fea3be ("build: add option to enable LTO")

Signed-off-by: David Marchand <david.marchand@redhat.com>
Acked-by: Thomas Monjalon <thomas@monjalon.net>