net/bnx2x: avoid undefined shift of 32-bit integer
The expression "0x1 << 31" is actually undefined since 0x1
is an integer not unsigned. Fix the general problem by using
the existing RTE_BIT32() macros instead.

Shows up as a cryptic warning when building with -Dbsanitize=undefined.
 error: case label does not reduce to an integer constant

Signed-off-by: Stephen Hemminger <stephen@networkplumber.org>