net/mvpp2: fix variable shadowing
[ upstream commit fc97ac545fcb5983dd9f6b5c9cc4a957968e8c8f ]

With shadowing warning enabled, we can see "i" was declared twice:

drivers/net/mvpp2/mrvl_ethdev.c: In function 'mrvl_rx_pkt_burst':
error: declaration of 'i' shadows a previous local [-Werror=shadow]
 2676 |                         int i;
      |                             ^
/mrvl_ethdev.c:2592:13: note: shadowed declaration is here
 2592 |         int i, ret, rx_done = 0;
      |             ^

Fixes: afb4d0d0bf91 ("net/mrvl: add Rx/Tx support")

Signed-off-by: Thomas Monjalon <thomas@monjalon.net>
Acked-by: David Marchand <david.marchand@redhat.com>
Acked-by: Bruce Richardson <bruce.richardson@intel.com>