dmadev: fix debug build with tracepoints
[ upstream commit 1624f34dde105a47e1d22f419a90fd65997c908f ]

Missing definition of errnos causes build failure:

In file included from ../lib/dmadev/rte_dmadev_trace.h:16,
                 from ../lib/dmadev/rte_dmadev_trace_points.c:8:
../lib/dmadev/rte_dmadev.h: In function ‘rte_dma_copy’:
../lib/dmadev/rte_dmadev.h:1183:25: error: ‘EINVAL’ undeclared
	(first use in this function)
 1183 |                 return -EINVAL;
      |                         ^~~~~~

Bugzilla ID: 1814
Fixes: 91e581e5c924 ("dmadev: add data plane API")

Signed-off-by: Stephen Hemminger <stephen@networkplumber.org>
Acked-by: Chengwen Feng <fengchengwen@huawei.com>