net/iavf: fix build with clang 21
[ upstream commit ffa370cf683a1dd37914a54b243ec38a237b3930 ]

Fix the following error seen with clang 21.1.4

drivers/net/intel/iavf/iavf_vchnl.c:123:38: error: variable
'notify_byte' is uninitialized when passed as a const pointer
argument here [-Werror,-Wuninitialized-const-pointer]

Fixes: cb5c1b91f76f ("net/iavf: add thread for event callbacks")

Signed-off-by: Jerin Jacob <jerinj@marvell.com>
Acked-by: Vladimir Medvedkin <vladimir.medvedkin@intel.com>
Reviewed-by: David Marchand <david.marchand@redhat.com>