hash: fix maybe-uninitialized warnings on build
[ upstream commit 32cdf0611b570b49fcee799d080656e3bfbed8e5 ]

Following recent changes to the test-meson-build.sh script[1] to use more
build-types warnings are seen in the hash library GFNI code about values
possibly being uninitialized.

In function ‘_mm512_mask_permutexvar_epi8’,
    inlined from ‘__rte_thash_gfni’ at ../lib/hash/rte_thash_x86_gfni.h:150:6:
/usr/lib/gcc/x86_64-linux-gnu/15/include/avx512vbmiintrin.h:97:20:
error: ‘tuple_bytes_2’ may be used uninitialized [-Werror=maybe-uninitialized]

These all appear to be a false positive, but fix these by explicitly
zero-initializing the offending values.

[1] 177acaf5cf75 ("devtools: test different build types")

Fixes: 4fd8c4cb0de1 ("hash: add new Toeplitz hash implementation")

Signed-off-by: Bruce Richardson <bruce.richardson@intel.com>
Acked-by: Vladimir Medvedkin <vladimir.medvedkin@intel.com>
Acked-by: David Marchand <david.marchand@redhat.com>