net/bnxt/tf_ulp: fix minsize build
[ upstream commit 374125fc8508efd83cfb6896639cc04e3e5d951c ]

This error is seen in build of type "minsize":

In function 'ulp_blob_append':
	error: 'num' may be used uninitialized [-Werror=maybe-uninitialized]
	drivers/net/bnxt/tf_ulp/ulp_utils.h:1109:13:
	note: in expansion of macro 'unlikely'
 1109 |         if (unlikely((src_offset + src_len) > num))
      |             ^~~~~~~~
drivers/net/bnxt/tf_ulp/ulp_utils.h:1105:18: note: 'num' was declared here
 1105 |         uint16_t num;

Indeed num may be not initialized if ulp_blob_data_get() fails.
It is fixed by checking the return value src_buf.

Fixes: 0c036a1485b9 ("net/bnxt/tf_ulp: optimize with inline and prediction")

Signed-off-by: Thomas Monjalon <thomas@monjalon.net>