power/intel_pstate: fix minsize build
This error is seen in build of type "minsize":

In function 'power_init_for_setting_freq',
	drivers/power/intel_pstate/intel_pstate_cpufreq.c:205:30:
	error: 'max_non_turbo' may be used uninitialized
		[-Werror=maybe-uninitialized]
drivers/power/intel_pstate/intel_pstate_cpufreq.c:122:18:
	note: 'max_non_turbo' was declared here
  122 |         uint64_t max_non_turbo;

It looks to be a compiler issue because we are not supposed
to reach this point in case of power_read_turbo_pct() failure.

The variable is initialized to allow compiling with "minsize" option.

Signed-off-by: Thomas Monjalon <thomas@monjalon.net>