dts: update params and parser docstrings
Address a few errors reported by Sphinx when generating documentation:
framework/params/__init__.py:docstring of framework.params.modify_str:3:
    WARNING: Inline interpreted text or phrase reference start-string
    without end-string.
framework/params/eal.py:docstring of framework.params.eal.EalParams:35:
    WARNING: Definition list ends without a blank line; unexpected
    unindent.
framework/params/types.py:docstring of framework.params.types:8:
    WARNING: Inline strong start-string without end-string.
framework/params/types.py:docstring of framework.params.types:9:
    WARNING: Inline strong start-string without end-string.
framework/parser.py:docstring of framework.parser.TextParser:33: ERROR:
    Unexpected indentation.
framework/parser.py:docstring of framework.parser.TextParser:43: ERROR:
    Unexpected indentation.
framework/parser.py:docstring of framework.parser.TextParser:49: ERROR:
    Unexpected indentation.
framework/parser.py:docstring of framework.parser.TextParser.wrap:8:
    ERROR: Unexpected indentation.
framework/parser.py:docstring of framework.parser.TextParser.wrap:9:
    WARNING: Block quote ends without a blank line; unexpected unindent.

Fixes: 87ba4cdc0dbb ("dts: use Unpack for type checking and hinting")
Fixes: d70159cb62f5 ("dts: add params manipulation module")
Fixes: 967fc62b0a43 ("dts: refactor EAL parameters class")
Fixes: 818fe14e3422 ("dts: add parsing utility module")

Signed-off-by: Juraj Linkeš <juraj.linkes@pantheon.tech>
Reviewed-by: Luca Vizzarro <luca.vizzarro@arm.com>
Reviewed-by: Jeremy Spewock <jspewock@iol.unh.edu>