eal: fix doxygen comments for UUID
[ upstream commit 61c7dfe75a9ab345bbd8bdc30c2da0ee661660a8 ]

Fix following syntax error reported by doxygen 1.9.5 version.

lib/eal/include/rte_uuid.h:89: error: RTE_UUID_STRLEN
has @param documentation sections but no arguments
(warning treated as error, aborting now)

Fixes: 6bc67c497a51 ("eal: add uuid API")

Signed-off-by: Jerin Jacob <jerinj@marvell.com>