vhost: fix build with GCC 4.8
Adds braces around initializer to resolve the following
false-positive build error with gcc 4.8.5 on CentOS:
lib/vhost/vduse.c:441:9: error: missing braces around initializer
  [-Werror=missing-braces]

Fixes: 653327e191f0 ("vhost: add multiqueue support to VDUSE")

Signed-off-by: Ali Alnubani <alialnu@nvidia.com>
Reviewed-by: Maxime Coquelin <maxime.coquelin@redhat.com>