net/ice: fix 32-bit build
[ upstream commit 910507de1164d1cb7051ddb84ac742bf088f4711 ]

Replace 'rte_memcpy' with 'memcpy' like other PMD code to avoid errors when
compiling with GCC-12 on 32-bit configure.

Compiler reports the follow error:

error: array subscript 8 is outside array bounds of "struct rte_mbuf *[32]"
[-Werror=array-bounds]

Fixes: c68a52b8b38c ("net/ice: support vector SSE in Rx")

Signed-off-by: Yiding Zhou <yidingx.zhou@intel.com>
Tested-by: Luca Boccassi <bluca@debian.org>