lib: fix backticks matching in Doxygen comments
[ upstream commit 2f8d3fda56754b13a09098fac1140d781366672f ]

Doxygen 1.15 detects valid errors. Fixing the same.

Example:
lib/eventdev/rte_event_timer_adapter.h:720: error: Reached end of file
while still searching closing '`' of a verbatim block starting at line
569 (warning treated as error, aborting now)

Fixes: a6562f6d6f8e ("eventdev: introduce event timer adapter")

Signed-off-by: Jerin Jacob <jerinj@marvell.com>
Acked-by: Stephen Hemminger <stephen@networkplumber.org>
Acked-by: Erik Gabriel Carrillo <erik.g.carrillo@intel.com>