bus/pci: fix minsize build
[ upstream commit 0cc620fbeff2889089f922c5218bc869600dfed2 ]

This error is seen in build of type "minsize":

In function 'pci_vfio_map_resource_secondary':
drivers/bus/pci/linux/pci_vfio.c:1005:28: error:
'maps' may be used uninitialized [-Werror=maybe-uninitialized]
 1005 |                 if (maps[j].addr)

On failure before assigning maps, it was trying to unmap.
The compiler should have detected that the unmap loop is a nop.

The fix is changing the goto destination after unmapping
to allow compiling with "minsize" option.

Signed-off-by: Thomas Monjalon <thomas@monjalon.net>