dpaa2: fix build with RTE_LIBRTE_IEEE1588
../drivers/net/dpaa2/dpaa2_rxtx.c: In function ‘dpaa2_dev_rx’:
../drivers/net/dpaa2/dpaa2_rxtx.c:863:4: error: ‘priv’ undeclared (first use in this function); did you mean ‘ldiv’?
    priv->rx_timestamp =
    ^~~~
    ldiv

Bugzilla ID: 982

Fixes: 1d10966a22ca ("net/dpaa2: fix timestamping for IEEE1588")

Signed-off-by: Luca Boccassi <bluca@debian.org>
Acked-by: Hemant Agrawal <hemant.agrawal@nxp.com>