common/mlx5: fix variable shadowing
[ upstream commit 2a9bcc306094e721b58af4887a5a1c887afcd4f4 ]

The word "unused" is too common for being used in a header.
There is a warning because a parameter is named "unused" in mbuf:

lib/mbuf/rte_mbuf.h: In function 'rte_mbuf_tx_offload':
error: declaration of 'unused' shadows a previous local [-Werror=shadow]
 1910 |         uint64_t ol3, uint64_t ol2, uint64_t unused)
      |                                     ~~~~~~~~~^~~~~~

Such value should be prefixed with "MLX5".

Fixes: bd935fe3e624 ("net/mlx5: wrap sampling actions per OS")

Signed-off-by: Thomas Monjalon <thomas@monjalon.net>
Acked-by: David Marchand <david.marchand@redhat.com>
Acked-by: Bruce Richardson <bruce.richardson@intel.com>