pmdinfogen: fix compilation with Clang 3.4.2 on CentOS 7
$ meson --werror --buildtype=debugoptimized build && ninja-build -C build
[..]
[5/2516] Compiling C object buildtools/pmdinfogen/pmdinfogen.p/pmdinfogen.c.o
FAILED: buildtools/pmdinfogen/pmdinfogen.p/pmdinfogen.c.o
clang -Ibuildtools/pmdinfogen/pmdinfogen.p -Ibuildtools/pmdinfogen -I../../root/dpdk/buildtools/pmdinfogen -I. -I../../root/dpdk -Iconfig -I../../root/dpdk/config -Ilib/librte_eal/include -I../../root/dpdk/lib/librte_eal/include -Ilib/librte_eal/linux/include -I../../root/dpdk/lib/librte_eal/linux/include -Ilib/librte_eal/x86/include -I../../root/dpdk/lib/librte_eal/x86/include -Ilib/librte_pci -I../../root/dpdk/lib/librte_pci -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -O2 -g -MD -MQ buildtools/pmdinfogen/pmdinfogen.p/pmdinfogen.c.o -MF buildtools/pmdinfogen/pmdinfogen.p/pmdinfogen.c.o.d -o buildtools/pmdinfogen/pmdinfogen.p/pmdinfogen.c.o -c ../../root/dpdk/buildtools/pmdinfogen/pmdinfogen.c
../../root/dpdk/buildtools/pmdinfogen/pmdinfogen.c:431:27: error: missing field 'hdr' initializer [-Werror,-Wmissing-field-initializers]
        struct elf_info info = {0};
                                 ^
1 error generated.
[..]

Use memset instead.

Bugzilla ID: 984

Fixes: 0decf84217f1 ("buildtools: zero elf info variable in pmdinfogen")

Signed-off-by: Luca Boccassi <bluca@debian.org>
Reviewed-by: Christian Ehrhardt <christian.ehrhardt@canonical.com>