eal/bsd: fix build on FreeBSD
Compilation on FreeBSD with clang was broken, giving the error message:

lib/librte_eal/bsdapp/eal/eal_pci.c:438:16: fatal error: assigning to
  'struct rte_pci_id *' from 'const struct rte_pci_id *' discards qualifiers
  [-Wincompatible-pointer-types-discards-qualifiers]
    for (id_table = dr->id_table ; id_table->vendor_id != 0; id_table++) {
                  ^ ~~~~~~~~~~~~

This patch fixes the issue by adding "const" to the type of id_table.

Fixes: 6065355a03fc ("pci: make device id tables const")

Signed-off-by: Bruce Richardson <bruce.richardson@intel.com>