mem: avoid hugepage path overflow
When constructing hugepage path, allocate the variable
to avoid a possible overflow which was detected in debug build:

In function 'find_numasocket':
lib/eal/linux/eal_memory.c:450:31:
	error: 'snprintf' output may be truncated
	before the last format character [-Werror=format-truncation=]
lib/eal/linux/eal_memory.c:449:9:
	note: 'snprintf' output 2 or more bytes (assuming 4097)
	into a destination of size 4096
  449 | snprintf(hugedir_str, sizeof(hugedir_str),
  450 |                 "%s/%s", hpi->hugedir, eal_get_hugefile_prefix());

This is a new warning (format-truncation) enabled in DPDK 26.03.

Bugzilla ID: 1878

Signed-off-by: Thomas Monjalon <thomas@monjalon.net>