common/mlx5: fix build on Linux in dlopen link mode
When using the Meson option "ibverbs_link=dlopen",
a glue library is built.

After the recent change requiring eal_export.h,
the build stopped because the internal EAL include directory
was unknown to this glue library:

	drivers/common/mlx5/linux/mlx5_glue.c:19:10: fatal error:
	eal_export.h: No such file or directory

Fixes: c7020bb20fc7 ("build: mark exported symbols")

Reported-by: Ali Alnubani <alialnu@nvidia.com>
Signed-off-by: Thomas Monjalon <thomas@monjalon.net>
Acked-by: David Marchand <david.marchand@redhat.com>