buildtools/cmdline: fix use in Meson subproject
Fix the following error when using dpdk as a subproject:

 subprojects/dpdk/buildtools/subproject/meson.build:28:56:
 ERROR: Unknown function "file".

This was obviously never tested in its submitted form.

Fixes: 7d8c608faa7f ("buildtools/cmdline: allow using script in subproject")
Cc: stable@dpdk.org

Signed-off-by: Robin Jarry <rjarry@redhat.com>
Acked-by: Bruce Richardson <bruce.richardson@intel.com>