net/octeon_ep: use intrinsic to access content of m128i
Compiler intrinsics should be used to access/manipulate contents
of __m128i.
Existing code results in the error below when compiled with MSVC:

../drivers/net/octeon_ep/cnxk_ep_rx_sse.c(61): error C2440:
    'type cast': cannot convert from '__m128i' to 'rte_xmm_t'

The fix is to use an intrinsic instead. This compiles fine with
gcc, clang and msvc.

Signed-off-by: Andre Muezerie <andremue@linux.microsoft.com>
Acked-by: Vamsi Attunuru <vattunuru@marvell.com>