test/power: fix build with shared library
Using private api `guest_channel_host_connect()`
will cause shared library build failure:
        test_power_kvm_vm.c:(.text+0x2cb):
        undefined reference to `guest_channel_host_connect'

So revert the changes done.

Fixes: d550a8cc31f3 ("app/test: enhance power manager unit tests")

Reported-by: Bruce Richardson <bruce.richardson@intel.com>
Suggested-by: David Hunt <david.hunt@intel.com>
Signed-off-by: Jananee Parthasarathy <jananeex.m.parthasarathy@intel.com>
Signed-off-by: Reshma Pattan <reshma.pattan@intel.com>