mbuf: fix build with GCC and history debug enabled
Message had extra newline which causes build failure
with GCC -DRTE_MBUF_HISTORY_DEBUG.

lib/mbuf/mbuf_history.c: In function ‘rte_mbuf_history_init’:
lib/log/rte_log.h:364:9: error:
  static assertion failed: "This log format string contains a \\n"
  364 | static_assert(!__builtin_strchr(fmt, '\n'), \
      | ^~~~~~~~~~~~~
lib/log/rte_log.h:387:9: note: in expansion of macro ‘RTE_LOG_CHECK_NO_NEWLINE’
  387 | RTE_LOG_CHECK_NO_NEWLINE(RTE_FMT_HEAD(__VA_ARGS__ ,)); \
      | ^~~~~~~~~~~~~~~~~~~~~~~~
lib/mbuf/mbuf_log.h:8:9: note: in expansion of macro ‘RTE_LOG_LINE’
    8 | RTE_LOG_LINE(level, MBUF, "" __VA_ARGS__)
      | ^~~~~~~~~~~~
lib/mbuf/mbuf_history.c:219:17: note: in expansion of macro ‘MBUF_LOG’
  219 | MBUF_LOG(ERR, "Failed to register mbuf history dynamic field: %s\n",

Fixes: d265a24a32a4 ("mbuf: record mbuf operations history")

Signed-off-by: Stephen Hemminger <stephen@networkplumber.org>