test/lcore: fix build with MSVC
MSVC warns about atomic qualifier:
../app/test/test_per_lcore.c(101): error C2220: the following warning is
	treated as an error
../app/test/test_per_lcore.c(101): warning C4090: 'function': different
	'_Atomic' qualifiers

Fixes: 7c37826c2b87 ("test/lcore: fix race in per-lcore test")

Signed-off-by: David Marchand <david.marchand@redhat.com>