examples/vhost: remove unused but set globals
The vhost example tracks number of queues but never uses the
variables. Remove num_queues and the num_vmdq_queues intermediate
that only fed it.

clang 23 reports:
vhost/main.c:86:17: error: variable 'num_queues' set but not used
         [-Werror,-Wunused-but-set-global]

Fixes: 84b02d16c539 ("examples/vhost: support new VMDQ API for i40e")
Cc: stable@dpdk.org

Signed-off-by: Stephen Hemminger <stephen@networkplumber.org>