app/testpmd: fix build with -O1
When configuring Meson with option "--optimization=1",
GCC complains "maybe-uninitialized" warning
and it was treated as error since Werror is enabled.

app/test-pmd/cmdline_flow.c:8678:53: error:
‘fp’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
 8678 |   action->dst.flex_handle = fp->flex_handle;
      |                             ~~^~~~~~~~~~~~~

Assign fp to NULL at declaration can avoid this.

Bugzilla ID: 1163
Fixes: c8e25fbf1440 ("ethdev: add flow flex modify")
Cc: stable@dpdk.org

Reported-by: Daxue Gao <daxuex.gao@intel.com>
Signed-off-by: Rongwei Liu <rongweil@nvidia.com>