net/mvpp2: fix build with IPv6 address structure
A structure has been created for IPv6 addresses
replacing the byte arrays of the IPv6 header.

This change was failing the compilation:
mrvl_flow.c:1055:29: error: incompatible type for argument 1 of 'memcmp'

Instead of adapting the memcmp call, a new function is used
to compare an IPv6 address with an unspec (zero) address.

Fixes: 89b5642d0d45 ("net: use IPv6 address structure for packet headers")

Signed-off-by: Thomas Monjalon <thomas@monjalon.net>