hash: fix build for x86 with GFNI
The file "rte_thash.c" uses the rte_cpu_get_flag_enabled() API
but does not include "rte_cpuflags.h".
Add the include to fix build issues this causes
on systems having GFNI (Galois Field New Instructions):

../lib/hash/rte_thash.c: In function ‘rte_thash_gfni_supported’:
../lib/hash/rte_thash.c:79:13: error: implicit declaration of function
‘rte_cpu_get_flag_enabled’ [-Wimplicit-function-declaration]
   79 |         if (rte_cpu_get_flag_enabled(RTE_CPUFLAG_GFNI) &&
         |             ^~~~~~~~~~~~~~~~~~~~~~~~

Fixes: e5b73e262f85 ("eal/x86: remove useless include from spinlock header")

Signed-off-by: Bruce Richardson <bruce.richardson@intel.com>