bbdev: enable with MSVC
The errors below popped up when compiling with MSVC:

../lib/bbdev/rte_bbdev.c(79): error C2061:
    syntax error: identifier 'TAILQ_ENTRY'
../lib/bbdev/rte_bbdev.c(85): error C2059:
    syntax error: '}'

This was caused by a missing include.

Signed-off-by: Andre Muezerie <andremue@linux.microsoft.com>
Reviewed-by: Maxime Coquelin <maxime.coquelin@redhat.com>