mldev: fix aarch32 build
Caught by UNH lab, cross compiling for aarch32:

../lib/mldev/mldev_utils_neon.c: In function
	'__float32_to_int8_neon_s8x8':
../lib/mldev/mldev_utils_neon.c:34:10: error: implicit declaration
	of function 'vcvtaq_s32_f32'; did you mean 'vcvtq_s32_f32'?
	[-Werror=implicit-function-declaration]
   34 |  s32x4 = vcvtaq_s32_f32(f32x4);
      |          ^~~~~~~~~~~~~~
      |          vcvtq_s32_f32
../lib/mldev/mldev_utils_neon.c:34:10: error: nested extern declaration
	of 'vcvtaq_s32_f32' [-Werror=nested-externs]
../lib/mldev/mldev_utils_neon.c:34:10: error: incompatible types when
	assigning to type 'int32x4_t' from type 'int'
../lib/mldev/mldev_utils_neon.c:42:10: error: incompatible types when
	assigning to type 'int32x4_t' from type 'int'
   42 |  s32x4 = vcvtaq_s32_f32(f32x4);
      |          ^~~~~~~~~~~~~~

Only compile NEON optimisation for aarch64.

Fixes: fc54766b1612 ("mldev: add Arm NEON type conversion")

Signed-off-by: David Marchand <david.marchand@redhat.com>