ring: silence GCC 12 warnings
[ upstream commit dea4c5415506b3c1996cc56dcf15ffb5f6f1d49c ]

gcc 12.2.1 on Fedora 37 is giving stringop-overread and stringop-overflow
warnings when compiled with --buildtype=debug e.g. [1].

They look similar to the overflow issues previously squashed in rte_memcpy
commit b5b3ea803e47 ("eal/x86: ignore gcc 10 stringop-overflow warnings").

Squash these warnings, waiting for a cleaner fix.

[1]
lib/ring/rte_ring_elem_pvt.h:100:25: error:
	‘memcpy’ reading 32 bytes from a region of size 4
	[-Werror=stringop-overread]
100 |               memcpy((void *)(ring + idx),
    |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
101 |                       (const void *)(obj + i), 32);
    |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

lib/ring/rte_ring_elem_pvt.h:234:25: error:
	‘memcpy’ writing 32 bytes into a region of size 4
	overflows the destination [-Werror=stringop-overflow=]
234 |               memcpy((void *)(obj + i), (void *)(ring + idx), 32);
    |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Kevin Traynor <ktraynor@redhat.com>
Signed-off-by: David Marchand <david.marchand@redhat.com>