rawdev: fix build with clang 21
Fix 16-bits formatting issues reported by clang 21 on Fedora 43:

../lib/rawdev/rte_rawdev.c:429:41: error: format specifies type
	'unsigned char' but the argument has type 'uint16_t'
	(aka 'unsigned short') [-Werror,-Wformat]
  429 |     RTE_RDEV_DEBUG("Start dev_id=%" PRIu8, dev_id);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~

../lib/rawdev/rte_rawdev.c:435:9: error: format specifies type
	'unsigned char' but the argument has type 'uint16_t'
	(aka 'unsigned short') [-Werror,-Wformat]
  434 |     RTE_RDEV_ERR("Device with dev_id=%" PRIu8 "already started",
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  435 |                  dev_id);
      |                  ^~~~~~~

../lib/rawdev/rte_rawdev.c:457:40: error: format specifies type
	'unsigned char' but the argument has type 'uint16_t'
	(aka 'unsigned short') [-Werror,-Wformat]
  457 |     RTE_RDEV_DEBUG("Stop dev_id=%" PRIu8, dev_id);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~

../lib/rawdev/rte_rawdev.c:464:4: error: format specifies type
	'unsigned char' but the argument has type 'uint16_t'
	(aka 'unsigned short') [-Werror,-Wformat]
  463 |     RTE_RDEV_ERR("Device with dev_id=%" PRIu8 "already stopped",
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  464 |             dev_id);
      |             ^~~~~~~

Fixes: c88b3f2558ed ("rawdev: introduce raw device library")
Cc: stable@dpdk.org

Signed-off-by: David Marchand <david.marchand@redhat.com>