net/bnxt: fix build with GCC 13
[ upstream commit bb7e1f17a6f3419725d11184e68749298205a8dc ]

GCC 13 complains with:

../../../dpdk/drivers/net/bnxt/tf_ulp/ulp_flow_db.c:962:1:
    error: conflicting types for ‘ulp_flow_db_flush_flows’ due to
    enum/integer mismatch; have ‘int32_t(struct bnxt_ulp_context *,
    enum bnxt_ulp_fdb_type)’ {aka ‘int(struct bnxt_ulp_context *,
    enum bnxt_ulp_fdb_type)’} [-Werror=enum-int-mismatch]
  962 | ulp_flow_db_flush_flows(struct bnxt_ulp_context *ulp_ctx,
      | ^~~~~~~~~~~~~~~~~~~~~~~
In file included from
../../../dpdk/drivers/net/bnxt/tf_ulp/ulp_flow_db.c:12:
../../../dpdk/drivers/net/bnxt/tf_ulp/ulp_flow_db.h:211:1: note:
    previous declaration of ‘ulp_flow_db_flush_flows’ with type
    ‘int32_t(struct bnxt_ulp_context *, uint32_t)’ {aka ‘int(struct
    bnxt_ulp_context *, unsigned int)’}
  211 | ulp_flow_db_flush_flows(struct bnxt_ulp_context *ulp_ctx,
      | ^~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Fixes: 30683082a8ed ("net/bnxt: combine default and regular flows")

Signed-off-by: David Marchand <david.marchand@redhat.com>
Reviewed-by: Ajit Khaparde <ajit.khaparde@broadcom.com>