net/nfp: fix double free in flow destroy
[ upstream commit fae5c633522efd30b6cb2c7a1bdfeb7e19e2f369 ]

Calling rte_free twice on same object will corrupt the heap.
Warning is:
In function 'nfp_pre_tun_table_check_del',
inlined from 'nfp_flow_destroy' at
	../drivers/net/nfp/flower/nfp_flower_flow.c:5143:9:
../drivers/net/nfp/flower/nfp_flower_flow.c:3830:9:
	error: pointer 'entry' used after 'rte_free'
	[-Werror=use-after-free]
3830 |         rte_free(entry);
     |         ^~~~~~~~~~~~~~~
../drivers/net/nfp/flower/nfp_flower_flow.c:3825:9:
	note: call to 'rte_free' here
3825 |         rte_free(entry);
     |         ^~~~~~~~~~~~~~~

Bugzilla ID: 1555
Fixes: d3c33bdf1f18 ("net/nfp: prepare for IPv4 UDP tunnel decap flow action")

Signed-off-by: Stephen Hemminger <stephen@networkplumber.org>
Acked-by: Morten Brørup <mb@smartsharesystems.com>
Acked-by: Konstantin Ananyev <konstantin.ananyev@huawei.com>
Acked-by: Wathsala Vithanage <wathsala.vithanage@arm.com>