net/i40e: fix missing RSS protocol support flag
Currently, i40e driver is missing the flag reporting RSS support for
plain IPv4. Configuring rss function to RTE_ETH_RSS_IPV4 returns an
error: "invalid rss hash function value", even though the HW supports
RSS on plain IPv4 traffic.

Fixes: a286ebeb0714 ("net/i40e: add dynamic mapping of SW flow types to HW pctypes")
Cc: stable@dpdk.org

Reported-by: Morten Brørup <mb@smartsharesystems.com>
Signed-off-by: Dhanya Pillai <dhanya.r.pillai@intel.com>
Acked-by: Bruce Richardson <bruce.richardson@intel.com>