config/arm: fix NVIDIA BlueField-3
The build was broken for BlueField-3:
	ERROR: Problem encountered:
	No suitable Arm mcpu name or custom mcpu definition object found.

ARM configuration requires explicit `mcpu` specifications
in the implementor description.

The patch adds `mcpu` and `flags` description
for the NVIDIA BlueField-3 configuration.

Fixes: c02c01dbf907 ("config/arm: prefer strict use of -mcpu if supported")

Signed-off-by: Gregory Etelson <getelson@nvidia.com>
Acked-by: Wathsala Vithanage <wathsala.vithanage@arm.com>