kni: fix build with Linux 6.8
strlcpy() was removed in commit d26270061ae6 (string: Remove strlcpy()), use
strscpy() instead.

The patches fixes this:
kernel/linux/kni/kni_net.c: In function ‘kni_get_drvinfo’:
kernel/linux/kni/kni_net.c:835:9: error: implicit declaration of function ‘strlcpy’; did you mean ‘strscpy’?

Intended esp. for stable/22.11. It should go wherever kni is still in
the tree.

Signed-off-by: Jiri Slaby <jslaby@suse.cz>
Acked-by: Luca Boccassi <bluca@debian.org>