argparse: fix minsize build
This error is seen in build of type "minsize":

In function 'parse_args', lib/argparse/rte_argparse.c:764:31: error:
'arg_idx' may be used uninitialized [-Werror=maybe-uninitialized]
  764 | if (arg_parsed[arg_idx] && !arg_attr_flag_multi(arg)) {
      |               ^

It looks to be a compiler issue because we are not supposed
to reach this point in case of find_option_arg() failure.

The variable is initialized to allow compiling with "minsize" option.

Signed-off-by: Thomas Monjalon <thomas@monjalon.net>
Acked-by: Chengwen Feng <fengchengwen@huawei.com>