examples/qos_sched: fix unused but set global errors
The QoS sched example tracks numa and port mask but never
uses them. Remove the dead code.

clang 23 reports:
qos_sched/args.c:26:17: error: variable 'app_numa_mask' set but not used
	 [-Werror,-Wunused-but-set-global]

Fixes: de3cfa2c9823 ("sched: initial import")
Cc: stable@dpdk.org

Signed-off-by: Stephen Hemminger <stephen@networkplumber.org>