dts: fix git tarball revision parsing
When running DTS with a git revision specified the following error occurs:
$ ./main.py --revision HEAD
[...]
FileNotFoundError: [Errno 2] No such file or directory:
     'dts/<framework.utils.DPDKGitTarball object at 0x78f69e73a5c0>'

Fix by casting DPDKGitTarball to Path, in order to stringify it correctly.

Bugzilla ID: 1496
Fixes: a23f22457dbd ("dts: constrain DPDK source argument")

Signed-off-by: Alex Chapman <alex.chapman@arm.com>
Reviewed-by: Jack Bond-Preston <jack.bond-preston@arm.com>
Reviewed-by: Luca Vizzarro <luca.vizzarro@arm.com>
Reviewed-by: Paul Szczepanek <paul.szczepanek@arm.com>
Reviewed-by: Juraj Linkeš <juraj.linkes@pantheon.tech>