net/iavf: fix minsize build
[ upstream commit 7c8bfad0ca350345a930d90365bb32f4de74a212 ]

This error is seen in build of type "minsize":

In function 'iavf_ipsec_crypto_supported':
    drivers/net/intel/iavf/iavf_ipsec_crypto.c:1649:29:
    error: status may be used uninitialized
        [-Werror=maybe-uninitialized]
 1649 | if (rc == 0 && status.status == INLINE_IPSEC_STATUS_AVAILABLE)
    drivers/net/intel/iavf/iavf_ipsec_crypto.c:1647:46:
    note: status was declared here
 1647 | struct virtchnl_ipsec_status status;

It looks to be a compiler issue because we are not supposed
to reach this point in case of iavf_ipsec_crypto_status_get() failure.

The variable is initialized to allow compiling with "minsize" option.

Signed-off-by: Thomas Monjalon <thomas@monjalon.net>